import Link from "next/link";
import TechStack from "@/app/components/shared-features/TechStack";
import {projectMetadata, projects} from "@/app/projects";
import {Metadata} from "next";

const slug = "ohmydosh"

export function generateMetadata(): Metadata {
    return projectMetadata(slug)
}

export default function OhMyDosh() {
    const {tech} = projects[slug] || null
    const h2_classes = "text-orange-500 font-bold text-3xl mt-30 mb-10"

    return (
        <article>
            <div className="flex items-center justify-center gap-5">
                <img src="/images/ohmydosh/omd-logo.svg"
                     alt="OhMyDosh logo"
                     width="300" height="50"
                     className="bg-white p-3 rounded-xl"
                />
            </div>

            <h2 className={h2_classes} id="what-was-it">What was OhMyDosh</h2>
            <p>
                OhMyDosh was very similar
                to <Link href="/projects/custard" className="text-accent">Custard</Link> (but came first).
                OhMyDosh was a website that gave the user
                cashback for taking offers and signing up for subscriptions and stuff.
                It never offered as many useful offers as other sites like
                TopCashback or Quidco. Mostly gambling and Amazon Prime Video offers which was probably why it
                was doomed.
            </p>

            <h2 className={h2_classes} id="improved-relaunch">Improved Relaunch</h2>
            <p>
                OMD was relaunched on the Kubernetes stack that Cashback was running on. We improved some of the
                frontend issues with Cashback for this site though with a refreshed frontend Tech Stack:
            </p>
            <ul className="list-disc ms-5 ps-5 mt-3 mb-3">
                <li><strong>Next.js</strong> SSR and SSG for improved SEO</li>
                <li><strong>Tailwind</strong> for class based helper styling</li>
                <li><strong>TypeScript</strong> for the type safety net, helping to prevent run time errors</li>
            </ul>
            <p>
                SEO was vastly improved over plain React, with Next.js (SSR and SSG) tech.  It allowed web crawlers to
                index pages better than the whole site being generated by JavaScript.
                We also implemented a lot of the SEO best practices that I had learned
                from working on Cashback, such as structured data, meta tags, and sitemap generation. As Cashback was
                more locked down, SEO wasn&apos;t as relevant.
                Learning to &apos;use client&apos; and resolving hydration errors were the main lessons.
            </p>

            <TechStack tech={tech}/>
        </article>
    )
}